### ISSUE TITLE
[Bug] timestamp too small

### ISSUE THREAD

**Issue by dominikhoebert** [RazgrizHsu/immich-mediakit#48]
### Pre-flight Checklist

- [x] I have searched existing issues and this is not a duplicate
- [x] I have read the documentation and troubleshooting guides

### Bug Description

Error when fetching:

"Error fetching assets for dominik, Failed to FetchAssets: timestamp too small (before year 1): '0001-12-30 00:53:56+00:53:28 BC': timestamp too small (before year 1): '0001-12-30 00:53:56+00:53:28 BC'"

Logs:

```
09:36:57.644|INFO| [modal] Confirm execution: id[fetch] cmd[fetch_asset]
09:36:57.644|INFO| [modal] Created task: id[fetch] cmd[fetch_asset]
09:36:57.703|INFO| [tws:ing] into id[fetch] name[Fetch] cmd[fetch_asset]
09:36:57.704|INFO| [tskMgr] Start sent: name[Fetch]
09:36:57.704|INFO| [tws:ing] started, tsn[1018df3c-2d53-44ac-9d3a-6ea537772ec7] tsk: {id:'fetch', cmd:'fetch_asset', args:{}, tsn:'1018df3c-2d53-44ac-9d3a-6ea537772ec7', name:'Fetch', msg:'Fetch assets from remote', nexts:[]}
09:36:57.750|INFO| [tws:uui] start: Fetch (tsn: 1018df3c-2d53-44ac-9d3a-6ea537772ec7) current tsk: {'id': 'fetch', 'cmd': 'fetch_asset', 'args': {}, 'tsn': None, 'name': 'Fetch', 'msg': 'Fetch assets from remote', 'nexts': []}
09:36:57.792|ERRO| Failed to FetchAssets: timestamp too small (before year 1): '0001-12-30 00:53:56+00:53:28 BC': timestamp too small (before year 1): '0001-12-30 00:53:56+00:53:28 BC'
09:36:57.792|ERRO| Traceback (most recent call last):
  File "/app/src/db/psql.py", line 248, in fetchAssets
    batch = cursor.fetchmany(szBatch)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/cursor.py", line 207, in fetchmany
    records = self._tx.load_rows(
              ^^^^^^^^^^^^^^^^^^^
  File "psycopg_binary/_psycopg/transform.pyx", line 462, in psycopg_binary._psycopg.Transformer.load_rows
  File "psycopg_binary/types/datetime.pyx", line 741, in psycopg_binary._psycopg.TimestamptzLoader.cload
psycopg.DataError: timestamp too small (before year 1): '0001-12-30 00:53:56+00:53:28 BC'
09:36:57.792|ERRO| [notify] Error fetching assets for dominik, Failed to FetchAssets: timestamp too small (before year 1): '0001-12-30 00:53:56+00:53:28 BC': timestamp too small (before year 1): '0001-12-30 00:53:56+00:53:28 BC'
09:36:57.794|INFO| [tskMgr] Complete sent: status[completed]
09:36:57.809|INFO| [tws:uui] prog[5.0] msg[Starting to fetch assets for dominik from PostgreSQL] 
09:36:57.883|INFO| [tws:uui] complete, ste[completed] chs[None]
09:36:57.955|INFO| [nav] sys:{ok:True}, disables: fth:False, vec:True, sim:True, view:True cnt:{ass:0, vec:0, simOk:0, simNo:0, simPnd:0}
09:36:57.974|INFO| [fth:status] cnt: {ass:0, vec:0, simOk:0, simNo:0, simPnd:0}
```

### Steps to Reproduce

Fetching

### Expected Behavior

Fetching

### Deployment Method

Docker Compose (same-host with Immich)

### Environment Information

Unraid
Docker compose

### Error Logs

```shell
09:36:57.644|INFO| [modal] Confirm execution: id[fetch] cmd[fetch_asset]
09:36:57.644|INFO| [modal] Created task: id[fetch] cmd[fetch_asset]
09:36:57.703|INFO| [tws:ing] into id[fetch] name[Fetch] cmd[fetch_asset]
09:36:57.704|INFO| [tskMgr] Start sent: name[Fetch]
09:36:57.704|INFO| [tws:ing] started, tsn[1018df3c-2d53-44ac-9d3a-6ea537772ec7] tsk: {id:'fetch', cmd:'fetch_asset', args:{}, tsn:'1018df3c-2d53-44ac-9d3a-6ea537772ec7', name:'Fetch', msg:'Fetch assets from remote', nexts:[]}
09:36:57.750|INFO| [tws:uui] start: Fetch (tsn: 1018df3c-2d53-44ac-9d3a-6ea537772ec7) current tsk: {'id': 'fetch', 'cmd': 'fetch_asset', 'args': {}, 'tsn': None, 'name': 'Fetch', 'msg': 'Fetch assets from remote', 'nexts': []}
09:36:57.792|ERRO| Failed to FetchAssets: timestamp too small (before year 1): '0001-12-30 00:53:56+00:53:28 BC': timestamp too small (before year 1): '0001-12-30 00:53:56+00:53:28 BC'
09:36:57.792|ERRO| Traceback (most recent call last):
  File "/app/src/db/psql.py", line 248, in fetchAssets
    batch = cursor.fetchmany(szBatch)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/cursor.py", line 207, in fetchmany
    records = self._tx.load_rows(
              ^^^^^^^^^^^^^^^^^^^
  File "psycopg_binary/_psycopg/transform.pyx", line 462, in psycopg_binary._psycopg.Transformer.load_rows
  File "psycopg_binary/types/datetime.pyx", line 741, in psycopg_binary._psycopg.TimestamptzLoader.cload
psycopg.DataError: timestamp too small (before year 1): '0001-12-30 00:53:56+00:53:28 BC'
09:36:57.792|ERRO| [notify] Error fetching assets for dominik, Failed to FetchAssets: timestamp too small (before year 1): '0001-12-30 00:53:56+00:53:28 BC': timestamp too small (before year 1): '0001-12-30 00:53:56+00:53:28 BC'
09:36:57.794|INFO| [tskMgr] Complete sent: status[completed]
09:36:57.809|INFO| [tws:uui] prog[5.0] msg[Starting to fetch assets for dominik from PostgreSQL] 
09:36:57.883|INFO| [tws:uui] complete, ste[completed] chs[None]
09:36:57.955|INFO| [nav] sys:{ok:True}, disables: fth:False, vec:True, sim:True, view:True cnt:{ass:0, vec:0, simOk:0, simNo:0, simPnd:0}
09:36:57.974|INFO| [fth:status] cnt: {ass:0, vec:0, simOk:0, simNo:0, simPnd:0}
```

### System Specifications

- [ ] Using GPU acceleration
- [ ] Large dataset (>10k images)
- [ ] Custom Qdrant configuration
- [ ] External PostgreSQL database
- [ ] Running behind proxy/reverse proxy
- [ ] Using custom Docker configuration

**Comment by RazgrizHsu** [comment]
Hi @dominikhoebert,

The issue has been fixed. Please pull the latest Docker image to get the update:

```bash
docker pull razghul/mediakit:latest
```

The fix adds timestamp filtering to prevent the "timestamp too small" error when fetching assets from the database. Assets with invalid timestamps (before year 1800) will now be automatically excluded from processing.

Please try fetching again and let me know if you encounter any further issues.

**Comment by dominikhoebert** [comment]
Hi @RazgrizHsu,

Thank you for your fast reply and the image update.

Unfortunately, the updated image did not change anything. I still get the same error.
Also, your Query
```sql
SELECT id, "originalPath", "createdAt" 
FROM asset 
WHERE "createdAt" < '0002-01-01'::timestamptz
  AND status = 'active' 
  AND type = 'IMAGE';
```
did not create any results.
I don't have any entries with createdAt before 2024.

**Comment by RazgrizHsu** [comment]
Hi @dominikhoebert,

Since `createdAt` fields are fine, the issue is likely with other timestamp fields. The `SELECT *` query fetches all timestamp columns, and any one of them with invalid values will cause the psycopg parsing error.

**Please check other timestamp fields:**
```sql
SELECT id, "originalPath", "createdAt", "updatedAt", "deletedAt", 
       "localDateTime", "fileCreatedAt", "fileModifiedAt"
FROM asset 
WHERE status = 'active' 
  AND type = 'IMAGE'
  AND (
    "updatedAt" < '1000-01-01'::timestamptz OR
    "deletedAt" < '1000-01-01'::timestamptz OR
    "localDateTime" < '1000-01-01'::timestamptz OR
    "fileCreatedAt" < '1000-01-01'::timestamptz OR
    "fileModifiedAt" < '1000-01-01'::timestamptz
  )
LIMIT 10;
```

This will help us identify which timestamp field contains the problematic `'0001-12-30 00:53:56+00:53:28 BC'` value that's causing the parsing error.
